apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-service-environment-config
  annotations:
    service.beta.openshift.io/inject-cabundle: true
data:
  VAULTKUBERNETESROLE: spi-oauth
  VAULTAPPROLESECRETNAME: vault-approle-spi-oauth
  VAULTAPPROLESECRETNAMESPACE: spi-system
